# The Lounge — Web IRC client

set positional-arguments := true

compose := "docker compose -f ../../../compose.yaml"

default:
    @just --list

add name:
    {{ compose }} exec atl-irc-client-lounge thelounge add {{name}}
list:
    {{ compose }} exec atl-irc-client-lounge thelounge list
reset name:
    {{ compose }} exec atl-irc-client-lounge thelounge reset {{name}}
logs:
    {{ compose }} logs -f atl-irc-client-lounge
restart:
    {{ compose }} restart atl-irc-client-lounge
