---
- name: Install node_exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Create systemd override directory
  ansible.builtin.file:
    path: /etc/systemd/system/prometheus-node-exporter.service.d
    state: directory
    mode: '0755'

- name: Deploy node_exporter systemd override
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/prometheus-node-exporter.service.d/override.conf
    mode: "0644"
  notify: Restart node_exporter

- name: Enable node_exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    enabled: true
    state: started
    daemon_reload: true

- name: Enable S.M.A.R.T. monitoring daemon
  ansible.builtin.systemd:
    name: smartmontools
    enabled: true
    state: started
  failed_when: false
  changed_when: false

- name: Enable hardware sensors daemon
  ansible.builtin.systemd:
    name: lm-sensors
    enabled: true
    state: started
  failed_when: false
  changed_when: false
