/**
 * Mailing list reader — seed sources and defaults.
 * Feed URLs: lore lists use `…/new.atom` (public-inbox).
 * Distro lists: only include feeds that return real RSS/Atom for server-side
 * `fetch` (no Varnish PoW, bot interstitials, or dead paths). Debian/Fedora
 * HyperKitty and Ubuntu Mailman2 `index.atom` URLs were removed for that reason.
 */

export type MailingListAdapterType =
  | "rss_atom"
  | "public_inbox"
  | "hyperkitty"
  | "html_archive";

export type MailingListVolumeClass = "high" | "medium" | "low";

export interface MailingListSeedSource {
  adapterType: MailingListAdapterType;
  archiveUrl: string;
  displayName: string;
  feedUrl: string | null;
  id: string;
  /** Short list name; shown after sourceLabel when both are set. */
  listLabel?: string;
  name: string;
  supportsPatchMeta: boolean;
  /** Origin / project (e.g. Debian, Kernel); emphasized in the UI when set with listLabel. */
  sourceLabel?: string;
  volumeClass: MailingListVolumeClass;
}

/** Revalidate RSS/Atom fetch for mailing list sync (seconds). */
export const MAILING_LIST_FETCH_REVALIDATE_SECONDS = 600;

/** Max items to ingest per sync per source. */
export const MAILING_LIST_ITEMS_PER_SYNC = 80;

/**
 * Seed (45). Lore slugs match https://lore.kernel.org/<slug>/ paths.
 * Non-lore: openSUSE / Arch HyperKitty RSS, Gentoo public-inbox Atom, Guix
 * (yhetil public-inbox), Mailman3 (WebKit, CPython).
 */
export const MAILING_LIST_SEED_SOURCES: MailingListSeedSource[] = [
  // High volume — lore
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/lkml/",
    displayName: "Linux Kernel (LKML)",
    feedUrl: "https://lore.kernel.org/lkml/new.atom",
    id: "lkml",
    listLabel: "LKML",
    name: "lkml",
    sourceLabel: "Kernel",
    supportsPatchMeta: true,
    volumeClass: "high",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/netdev/",
    displayName: "netdev",
    feedUrl: "https://lore.kernel.org/netdev/new.atom",
    id: "netdev",
    listLabel: "netdev",
    name: "netdev",
    sourceLabel: "Kernel",
    supportsPatchMeta: true,
    volumeClass: "high",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/linux-next/",
    displayName: "linux-next",
    feedUrl: "https://lore.kernel.org/linux-next/new.atom",
    id: "linux-next",
    listLabel: "linux-next",
    name: "linux-next",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "high",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/linux-arm-kernel/",
    displayName: "linux-arm-kernel",
    feedUrl: "https://lore.kernel.org/linux-arm-kernel/new.atom",
    id: "linux-arm-kernel",
    listLabel: "linux-arm-kernel",
    name: "linux-arm-kernel",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "high",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/linux-wireless/",
    displayName: "linux-wireless",
    feedUrl: "https://lore.kernel.org/linux-wireless/new.atom",
    id: "linux-wireless",
    listLabel: "linux-wireless",
    name: "linux-wireless",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "high",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/bpf/",
    displayName: "bpf",
    feedUrl: "https://lore.kernel.org/bpf/new.atom",
    id: "bpf",
    listLabel: "bpf",
    name: "bpf",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "high",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/dri-devel/",
    displayName: "dri-devel",
    feedUrl: "https://lore.kernel.org/dri-devel/new.atom",
    id: "dri-devel",
    listLabel: "dri-devel",
    name: "dri-devel",
    sourceLabel: "Kernel",
    supportsPatchMeta: true,
    volumeClass: "high",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/linux-scsi/",
    displayName: "linux-scsi",
    feedUrl: "https://lore.kernel.org/linux-scsi/new.atom",
    id: "linux-scsi",
    listLabel: "linux-scsi",
    name: "linux-scsi",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "high",
  },
  // Medium — lore
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/linux-mm/",
    displayName: "linux-mm",
    feedUrl: "https://lore.kernel.org/linux-mm/new.atom",
    id: "linux-mm",
    listLabel: "linux-mm",
    name: "linux-mm",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/linux-pci/",
    displayName: "linux-pci",
    feedUrl: "https://lore.kernel.org/linux-pci/new.atom",
    id: "linux-pci",
    listLabel: "linux-pci",
    name: "linux-pci",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/linux-usb/",
    displayName: "linux-usb",
    feedUrl: "https://lore.kernel.org/linux-usb/new.atom",
    id: "linux-usb",
    listLabel: "linux-usb",
    name: "linux-usb",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/linux-fsdevel/",
    displayName: "linux-fsdevel",
    feedUrl: "https://lore.kernel.org/linux-fsdevel/new.atom",
    id: "linux-fsdevel",
    listLabel: "linux-fsdevel",
    name: "linux-fsdevel",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/linux-nvme/",
    displayName: "linux-nvme",
    feedUrl: "https://lore.kernel.org/linux-nvme/new.atom",
    id: "linux-nvme",
    listLabel: "linux-nvme",
    name: "linux-nvme",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/linux-crypto/",
    displayName: "linux-crypto",
    feedUrl: "https://lore.kernel.org/linux-crypto/new.atom",
    id: "linux-crypto",
    listLabel: "linux-crypto",
    name: "linux-crypto",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/kvm/",
    displayName: "kvm",
    feedUrl: "https://lore.kernel.org/kvm/new.atom",
    id: "kvm",
    listLabel: "kvm",
    name: "kvm",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/linux-block/",
    displayName: "linux-block",
    feedUrl: "https://lore.kernel.org/linux-block/new.atom",
    id: "linux-block",
    listLabel: "linux-block",
    name: "linux-block",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/linux-rdma/",
    displayName: "linux-rdma",
    feedUrl: "https://lore.kernel.org/linux-rdma/new.atom",
    id: "linux-rdma",
    listLabel: "linux-rdma",
    name: "linux-rdma",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/linux-efi/",
    displayName: "linux-efi",
    feedUrl: "https://lore.kernel.org/linux-efi/new.atom",
    id: "linux-efi",
    listLabel: "linux-efi",
    name: "linux-efi",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/linux-kbuild/",
    displayName: "linux-kbuild",
    feedUrl: "https://lore.kernel.org/linux-kbuild/new.atom",
    id: "linux-kbuild",
    listLabel: "linux-kbuild",
    name: "linux-kbuild",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/linux-doc/",
    displayName: "linux-doc",
    feedUrl: "https://lore.kernel.org/linux-doc/new.atom",
    id: "linux-doc",
    listLabel: "linux-doc",
    name: "linux-doc",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "low",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/rust-for-linux/",
    displayName: "rust-for-linux",
    feedUrl: "https://lore.kernel.org/rust-for-linux/new.atom",
    id: "rust-for-linux",
    listLabel: "rust-for-linux",
    name: "rust-for-linux",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  // Lore — release, cross-distro, embedded, security, virt, tooling
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/stable/",
    displayName: "Linux stable",
    feedUrl: "https://lore.kernel.org/stable/new.atom",
    id: "stable",
    listLabel: "stable",
    name: "stable",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/regressions/",
    displayName: "Linux regressions",
    feedUrl: "https://lore.kernel.org/regressions/new.atom",
    id: "regressions",
    listLabel: "regressions",
    name: "regressions",
    sourceLabel: "Kernel",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/distributions/",
    displayName: "distributions",
    feedUrl: "https://lore.kernel.org/distributions/new.atom",
    id: "distributions",
    listLabel: "distributions",
    name: "distributions",
    sourceLabel: "Linux",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/containers/",
    displayName: "containers",
    feedUrl: "https://lore.kernel.org/containers/new.atom",
    id: "containers",
    listLabel: "containers",
    name: "containers",
    sourceLabel: "Linux",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/buildroot/",
    displayName: "buildroot",
    feedUrl: "https://lore.kernel.org/buildroot/new.atom",
    id: "buildroot",
    listLabel: "buildroot",
    name: "buildroot",
    sourceLabel: "Embedded",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/yocto/",
    displayName: "yocto",
    feedUrl: "https://lore.kernel.org/yocto/new.atom",
    id: "yocto",
    listLabel: "yocto",
    name: "yocto",
    sourceLabel: "Embedded",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/openembedded-core/",
    displayName: "openembedded-core",
    feedUrl: "https://lore.kernel.org/openembedded-core/new.atom",
    id: "openembedded-core",
    listLabel: "openembedded-core",
    name: "openembedded-core",
    sourceLabel: "Embedded",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/openembedded-devel/",
    displayName: "openembedded-devel",
    feedUrl: "https://lore.kernel.org/openembedded-devel/new.atom",
    id: "openembedded-devel",
    listLabel: "openembedded-devel",
    name: "openembedded-devel",
    sourceLabel: "Embedded",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/selinux/",
    displayName: "selinux",
    feedUrl: "https://lore.kernel.org/selinux/new.atom",
    id: "selinux",
    listLabel: "selinux",
    name: "selinux",
    sourceLabel: "SELinux",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/selinux-refpolicy/",
    displayName: "selinux-refpolicy",
    feedUrl: "https://lore.kernel.org/selinux-refpolicy/new.atom",
    id: "selinux-refpolicy",
    listLabel: "refpolicy",
    name: "selinux-refpolicy",
    sourceLabel: "SELinux",
    supportsPatchMeta: false,
    volumeClass: "low",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/qemu-devel/",
    displayName: "qemu-devel",
    feedUrl: "https://lore.kernel.org/qemu-devel/new.atom",
    id: "qemu-devel",
    listLabel: "qemu-devel",
    name: "qemu-devel",
    sourceLabel: "Virtualization",
    supportsPatchMeta: false,
    volumeClass: "high",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/virtio-dev/",
    displayName: "virtio-dev",
    feedUrl: "https://lore.kernel.org/virtio-dev/new.atom",
    id: "virtio-dev",
    listLabel: "virtio-dev",
    name: "virtio-dev",
    sourceLabel: "Virtualization",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/virtio-fs/",
    displayName: "virtio-fs",
    feedUrl: "https://lore.kernel.org/virtio-fs/new.atom",
    id: "virtio-fs",
    listLabel: "virtio-fs",
    name: "virtio-fs",
    sourceLabel: "Virtualization",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://lore.kernel.org/git/",
    displayName: "git",
    feedUrl: "https://lore.kernel.org/git/new.atom",
    id: "git",
    listLabel: "git",
    name: "git",
    sourceLabel: "Git",
    supportsPatchMeta: false,
    volumeClass: "high",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://yhetil.org/guix-devel/",
    displayName: "Guix development",
    feedUrl: "https://yhetil.org/guix-devel/new.atom",
    id: "guix-devel",
    listLabel: "guix-devel",
    name: "guix-devel",
    sourceLabel: "Guix",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  // Medium — distro (working RSS; no PoW/bot interstitial on feed URL)
  {
    adapterType: "rss_atom",
    archiveUrl:
      "https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/",
    displayName: "openSUSE Factory",
    feedUrl:
      "https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/feed/",
    id: "opensuse-factory",
    listLabel: "Factory",
    name: "opensuse-factory",
    sourceLabel: "openSUSE",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  // Low — distro / announce-friendly
  {
    adapterType: "rss_atom",
    archiveUrl:
      "https://lists.archlinux.org/archives/list/arch-dev-public@lists.archlinux.org/",
    displayName: "Arch arch-dev-public",
    feedUrl:
      "https://lists.archlinux.org/archives/list/arch-dev-public@lists.archlinux.org/feed/",
    id: "arch-dev-public",
    listLabel: "arch-dev-public",
    name: "arch-dev-public",
    sourceLabel: "Arch",
    supportsPatchMeta: false,
    volumeClass: "low",
  },
  {
    adapterType: "rss_atom",
    archiveUrl:
      "https://lists.archlinux.org/archives/list/aur-general@lists.archlinux.org/",
    displayName: "Arch aur-general",
    feedUrl:
      "https://lists.archlinux.org/archives/list/aur-general@lists.archlinux.org/feed/",
    id: "aur-general",
    listLabel: "aur-general",
    name: "aur-general",
    sourceLabel: "Arch",
    supportsPatchMeta: false,
    volumeClass: "low",
  },
  {
    adapterType: "rss_atom",
    archiveUrl:
      "https://lists.archlinux.org/archives/list/arch-general@lists.archlinux.org/",
    displayName: "Arch arch-general",
    feedUrl:
      "https://lists.archlinux.org/archives/list/arch-general@lists.archlinux.org/feed/",
    id: "arch-general",
    listLabel: "arch-general",
    name: "arch-general",
    sourceLabel: "Arch",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
  {
    adapterType: "rss_atom",
    archiveUrl:
      "https://lists.archlinux.org/archives/list/arch-announce@lists.archlinux.org/",
    displayName: "Arch arch-announce",
    feedUrl:
      "https://lists.archlinux.org/archives/list/arch-announce@lists.archlinux.org/feed/",
    id: "arch-announce",
    listLabel: "arch-announce",
    name: "arch-announce",
    sourceLabel: "Arch",
    supportsPatchMeta: false,
    volumeClass: "low",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://archives.gentoo.org/gentoo-dev/",
    displayName: "Gentoo dev",
    feedUrl: "https://archives.gentoo.org/gentoo-dev/new.atom",
    id: "gentoo-dev",
    listLabel: "dev",
    name: "gentoo-dev",
    sourceLabel: "Gentoo",
    supportsPatchMeta: false,
    volumeClass: "low",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://archives.gentoo.org/gentoo-announce/",
    displayName: "Gentoo announce",
    feedUrl: "https://archives.gentoo.org/gentoo-announce/new.atom",
    id: "gentoo-announce",
    listLabel: "announce",
    name: "gentoo-announce",
    sourceLabel: "Gentoo",
    supportsPatchMeta: false,
    volumeClass: "low",
  },
  // Projects — Mailman3 RSS
  {
    adapterType: "rss_atom",
    archiveUrl:
      "https://lists.webkit.org/archives/list/webkit-dev@lists.webkit.org/",
    displayName: "WebKit webkit-dev",
    feedUrl:
      "https://lists.webkit.org/archives/list/webkit-dev@lists.webkit.org/feed/",
    id: "webkit-dev",
    listLabel: "webkit-dev",
    name: "webkit-dev",
    sourceLabel: "WebKit",
    supportsPatchMeta: false,
    volumeClass: "high",
  },
  {
    adapterType: "rss_atom",
    archiveUrl: "https://mail.python.org/archives/list/python-dev@python.org/",
    displayName: "Python python-dev",
    feedUrl:
      "https://mail.python.org/archives/list/python-dev@python.org/feed/",
    id: "python-dev",
    listLabel: "python-dev",
    name: "python-dev",
    sourceLabel: "Python",
    supportsPatchMeta: false,
    volumeClass: "high",
  },
  // FreeBSD archives (mlmmj HTML)
  {
    adapterType: "html_archive",
    archiveUrl: "https://lists.freebsd.org/archives/freebsd-announce/",
    displayName: "FreeBSD freebsd-announce",
    feedUrl: "https://lists.freebsd.org/archives/freebsd-announce/",
    id: "freebsd-announce",
    listLabel: "freebsd-announce",
    name: "freebsd-announce",
    sourceLabel: "FreeBSD",
    supportsPatchMeta: false,
    volumeClass: "low",
  },
  {
    adapterType: "html_archive",
    archiveUrl: "https://lists.freebsd.org/archives/freebsd-current/",
    displayName: "FreeBSD freebsd-current",
    feedUrl: "https://lists.freebsd.org/archives/freebsd-current/",
    id: "freebsd-current",
    listLabel: "freebsd-current",
    name: "freebsd-current",
    sourceLabel: "FreeBSD",
    supportsPatchMeta: false,
    volumeClass: "high",
  },
  {
    adapterType: "html_archive",
    archiveUrl: "https://lists.freebsd.org/archives/freebsd-hackers/",
    displayName: "FreeBSD freebsd-hackers",
    feedUrl: "https://lists.freebsd.org/archives/freebsd-hackers/",
    id: "freebsd-hackers",
    listLabel: "freebsd-hackers",
    name: "freebsd-hackers",
    sourceLabel: "FreeBSD",
    supportsPatchMeta: false,
    volumeClass: "high",
  },
  // OpenBSD archives via MARC
  {
    adapterType: "html_archive",
    archiveUrl: "https://marc.info/?l=openbsd-announce",
    displayName: "OpenBSD openbsd-announce",
    feedUrl: "https://marc.info/?l=openbsd-announce",
    id: "openbsd-announce",
    listLabel: "openbsd-announce",
    name: "openbsd-announce",
    sourceLabel: "OpenBSD",
    supportsPatchMeta: false,
    volumeClass: "low",
  },
  {
    adapterType: "html_archive",
    archiveUrl: "https://marc.info/?l=openbsd-misc",
    displayName: "OpenBSD openbsd-misc",
    feedUrl: "https://marc.info/?l=openbsd-misc",
    id: "openbsd-misc",
    listLabel: "openbsd-misc",
    name: "openbsd-misc",
    sourceLabel: "OpenBSD",
    supportsPatchMeta: false,
    volumeClass: "high",
  },
  {
    adapterType: "html_archive",
    archiveUrl: "https://marc.info/?l=openbsd-tech",
    displayName: "OpenBSD openbsd-tech",
    feedUrl: "https://marc.info/?l=openbsd-tech",
    id: "openbsd-tech",
    listLabel: "openbsd-tech",
    name: "openbsd-tech",
    sourceLabel: "OpenBSD",
    supportsPatchMeta: false,
    volumeClass: "medium",
  },
];
