"""Core domain primitives: constants, events, errors, protocols."""

from bridge.core.constants import ORIGINS, ProtocolOrigin
from bridge.core.errors import BridgeConfigurationError, BridgeError
from bridge.core.events import (
    BridgeAdapter,
    ConfigReload,
    Dispatcher,
    EventTarget,
    Join,
    MessageDelete,
    MessageDeleteOut,
    MessageIn,
    MessageOut,
    Part,
    Quit,
    ReactionIn,
    ReactionOut,
    TypingIn,
    TypingOut,
    config_reload,
    dispatcher,  # noqa: F401
    join,
    message_delete,
    message_delete_out,
    message_in,
    message_out,
    part,
    quit,
    reaction_in,
    reaction_out,
    typing_in,
    typing_out,
)

__all__ = [
    "ORIGINS",
    "BridgeAdapter",
    "BridgeConfigurationError",
    "BridgeError",
    "ConfigReload",
    "Dispatcher",
    "EventTarget",
    "Join",
    "MessageDelete",
    "MessageDeleteOut",
    "MessageIn",
    "MessageOut",
    "Part",
    "ProtocolOrigin",
    "Quit",
    "ReactionIn",
    "ReactionOut",
    "TypingIn",
    "TypingOut",
    "config_reload",
    "join",
    "message_delete",
    "message_delete_out",
    "message_in",
    "message_out",
    "part",
    "quit",
    "reaction_in",
    "reaction_out",
    "typing_in",
    "typing_out",
]
